import type { Recipe } from "./types";

const sourceRecipes: Omit<Recipe, "photo">[] = [
  {
    id: "pasta-broccoli-zalm", name: "Pasta-ovenschotel met broccoli en zalm", source: "Picnic",
    type: "Oven", time: 40, serv: 4, kcal: 705, p: 39, c: 58, f: 36, est: true,
    base: "#E9D6A9", pal: ["#E8836B", "#4E9A4A", "#E7B84E", "#7FB77E", "#F4EFE6"], drizzle: false,
    ing: [
      { n: "Zalmfilet zonder huid", a: 300, u: "g", c: "vv" }, { n: "Broccoli", a: 1, u: "stuk", c: "gf" },
      { n: "Prei (gesneden)", a: 200, u: "g", c: "gf" }, { n: "Fusilli", a: 300, u: "g", c: "pg" },
      { n: "Bechamelsaus", a: 200, u: "ml", c: "sk" }, { n: "Geraspte kaas", a: 175, u: "g", c: "zk" },
      { n: "Knoflook", a: 2, u: "teen", c: "gf" }, { n: "Olijfolie", a: 2, u: "el", c: "sk" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Verwarm de oven voor op 200°C.",
      "Kook de fusilli in ruim water beetgaar (ca. 6 min). Voeg de laatste 3 minuten de broccoliroosjes toe en giet daarna alles af.",
      "Snijd de prei in ringen en snipper de knoflook. Fruit ze kort glazig in de olijfolie.",
      "Meng de afgegoten pasta en broccoli met de prei, knoflook en bechamelsaus. Breng op smaak met peper en zout.",
      "Schep het mengsel in een ovenschaal en bestrooi met de geraspte kaas.",
      "Snijd de zalm in blokjes en verdeel over de schotel; druk licht aan.",
      "Bak de ovenschotel ca. 20 min in het midden van de oven tot de kaas gesmolten en goudbruin is."],
  },
  {
    id: "sweet-chilli-slaw", name: "Sweet Chilli Chicken Slaw Bowls", source: "MacroFit",
    type: "Bowl", time: 25, serv: 4, kcal: 410, p: 36, c: 42, f: 10,
    base: "#EFE6CF", pal: ["#C85B2E", "#8E5AA0", "#F2C94C", "#7FB77E", "#E08A3C"], drizzle: true,
    ing: [
      { n: "Kipfilet", a: 500, u: "g", c: "vv" }, { n: "Rijst (gekookt)", a: 2, u: "cup", c: "pg" },
      { n: "Koolslamix", a: 1, u: "zak", c: "gf" }, { n: "Mais", a: 0.5, u: "cup", c: "gf" },
      { n: "Komkommer", a: 0.5, u: "stuk", c: "gf" }, { n: "Sweet chilli saus", a: 2, u: "el", c: "sk" },
      { n: "Light mayonaise", a: 0.25, u: "cup", c: "sk" }, { n: "Knoflookpoeder", a: 1, u: "tl", c: "sk" },
      { n: "Lente-ui", a: 2, u: "stuk", c: "gf" }, { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Kook de rijst volgens de verpakking.", "Bak de kip met knoflookpoeder, peper en zout.",
      "Meng de kip met sweet chilli saus tot glazig.", "Vul de kommen met rijst, koolslaw, mais en komkommer.",
      "Top met kip, mayonaise en lente-ui."],
  },
  {
    id: "kip-teriyaki-rijst", name: "Kip Teriyaki met Rijst", source: "Eiwitrijke Recepten NL",
    type: "Bowl", time: 20, serv: 1, kcal: 480, p: 42, c: 55, f: 9, est: true,
    base: "#EFE6CF", pal: ["#B96A2A", "#4E9A4A", "#E08A3C", "#D14A3A"], drizzle: false,
    ing: [
      { n: "Kipfilet", a: 150, u: "g", c: "vv" }, { n: "Rijst", a: 75, u: "g", c: "pg" },
      { n: "Wokgroente", a: 150, u: "g", c: "gf" }, { n: "Sojasaus", a: 1, u: "el", c: "sk" },
      { n: "Honing", a: null, u: "", c: "sk" }, { n: "Knoflook", a: 1, u: "teen", c: "gf" },
    ],
    steps: ["Kook de rijst gaar.", "Bak de kip bruin.", "Voeg de groente toe.", "Roer de saus erdoor.", "Laat kort indikken."],
  },
  {
    id: "big-mac-wrap", name: "Big Mac Wrap", source: "De Snelle Keuken",
    type: "Wrap", time: 15, serv: 1, kcal: 520, p: 32, c: 38, f: 24,
    base: "#E9D6A9", pal: ["#7A4A33", "#F2C94C", "#6DA84F", "#F2E7C0", "#C0433A"], drizzle: true,
    ing: [
      { n: "Grote tortilla wrap", a: 1, u: "stuk", c: "br" }, { n: "Rundergehakt", a: 100, u: "g", c: "vv" },
      { n: "Cheddar", a: 1, u: "plak", c: "zk" }, { n: "IJsbergsla", a: 1, u: "handje", c: "gf" },
      { n: "Augurk", a: 20, u: "g", c: "gf" }, { n: "Ui", a: 20, u: "g", c: "gf" },
      { n: "Light mayonaise", a: 1, u: "el", c: "sk" }, { n: "Ketchup", a: 1, u: "tl", c: "sk" },
      { n: "Mosterd", a: 1, u: "tl", c: "sk" }, { n: "Augurkensap", a: 1, u: "tl", c: "sk" },
      { n: "Paprikapoeder", a: null, u: "", c: "sk" }, { n: "Knoflookpoeder", a: null, u: "", c: "sk" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Druk het gehakt dun uit over de wrap.", "Kruid met peper en zout.",
      "Bak de wrap met het gehakt naar beneden in een pan.", "Draai om en leg de cheddar op het vlees.",
      "Meng alle ingrediënten voor de burgersaus.", "Beleg met ijsbergsla, ui, augurk en saus.",
      "Vouw dubbel en bak nog kort tot de wrap licht krokant is."],
  },
  {
    id: "creamy-steak-pasta", name: "Creamy Steak Pasta", source: "De Snelle Keuken",
    type: "Pasta", time: 20, serv: 1, kcal: 560, p: 42, c: 55, f: 18,
    base: "#E9D6A0", pal: ["#7A4A33", "#6E5B47", "#4E9A4A", "#B5654E"], drizzle: false,
    ing: [
      { n: "Pasta", a: 75, u: "g", c: "pg" }, { n: "Biefstuk", a: 125, u: "g", c: "vv" },
      { n: "Champignons", a: 100, u: "g", c: "gf" }, { n: "Knoflook", a: 1, u: "teen", c: "gf" },
      { n: "Kookroom light", a: 50, u: "ml", c: "zk" }, { n: "Kruidenroomkaas light", a: 25, u: "g", c: "zk" },
      { n: "Parmezaanse kaas", a: 10, u: "g", c: "zk" }, { n: "Verse peterselie", a: null, u: "", c: "gf" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Kook de pasta volgens de verpakking.", "Kruid de biefstuk met peper en zout en bak kort in een hete pan.",
      "Bak in dezelfde pan de champignons en knoflook.", "Voeg light kookroom en Parmezaanse kaas toe en laat kort indikken.",
      "Meng de pasta door de saus.", "Snijd de biefstuk in plakjes en leg ze bovenop de pasta."],
  },
  {
    id: "gezonde-kapsalon", name: "Gezonde Kapsalon", source: "FIT OP JE BORD",
    type: "Oven", time: 45, serv: 2, kcal: 615, p: 47, c: 63, f: 17,
    base: "#E9E3D6", pal: ["#E3B24E", "#C97A2B", "#F2C94C", "#D14A3A", "#7FB77E", "#9C5AA0"], drizzle: true,
    ing: [
      { n: "Aardappelen (kruimig)", a: 400, u: "g", c: "gf" }, { n: "Olijfolie", a: 1, u: "el", c: "sk" },
      { n: "Kipfilet", a: 300, u: "g", c: "vv" }, { n: "Shoarmakruiden", a: 1, u: "el", c: "sk" },
      { n: "Knoflook", a: 2, u: "teen", c: "gf" }, { n: "Rode ui", a: 0.5, u: "stuk", c: "gf" },
      { n: "Geraspte 30+ kaas", a: 100, u: "g", c: "zk" }, { n: "Komkommer", a: 0.5, u: "stuk", c: "gf" },
      { n: "Cherrytomaatjes", a: 1, u: "handje", c: "gf" }, { n: "IJsbergsla", a: 75, u: "g", c: "gf" },
      { n: "Magere kwark", a: 150, u: "g", c: "zk" }, { n: "Citroensap", a: 1, u: "tl", c: "sk" },
      { n: "Verse peterselie", a: null, u: "", c: "gf" }, { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Verwarm de oven voor op 200°C.", "Schil de aardappelen of was ze goed en snijd in frieten.",
      "Meng de frieten met olijfolie, zout en peper.", "Verdeel over een bakplaat en bak 25-30 min tot goudbruin en knapperig.",
      "Snijd ondertussen de kipfilet in reepjes en meng met shoarmakruiden.", "Verhit een koekenpan en bak de kip 6-8 min gaar en goudbruin.",
      "Meng voor de knoflooksaus alle ingrediënten en zet in de koelkast.", "Haal de frietjes uit de oven, verdeel de kip erover, strooi de kaas erover en zet 5 min terug tot de kaas gesmolten is.",
      "Beleg met ijsbergsla, komkommer, rode ui en cherrytomaatjes. Garneer met knoflooksaus."],
  },
  {
    id: "teriyaki-rice-bowl", name: "Teriyaki Chicken Rice Bowl", source: "De Snelle Keuken",
    type: "Bowl", time: 20, serv: 1, kcal: 520, p: 45, c: 58, f: 12,
    base: "#EFE6CF", pal: ["#B96A2A", "#7FB77E", "#5C9A3F", "#EDE3C8"], drizzle: false,
    ing: [
      { n: "Zilvervliesrijst", a: 75, u: "g", c: "pg" }, { n: "Kipfilet", a: 150, u: "g", c: "vv" },
      { n: "Komkommer", a: 50, u: "g", c: "gf" }, { n: "Doperwten", a: 40, u: "g", c: "gf" },
      { n: "Lente-ui", a: 1, u: "stuk", c: "gf" }, { n: "Sesamzaad", a: 1, u: "tl", c: "sk" },
      { n: "Olie", a: 1, u: "tl", c: "sk" }, { n: "Teriyaki saus", a: 2, u: "el", c: "sk" },
      { n: "Sojasaus", a: 1, u: "tl", c: "sk" }, { n: "Honing", a: 1, u: "tl", c: "sk" },
      { n: "Peper, zout & knoflookpoeder", a: null, u: "", c: "sk" },
    ],
    steps: ["Kook de rijst volgens de verpakking.", "Snijd de kip in stukjes en kruid met peper, zout en knoflookpoeder.",
      "Bak de kip goudbruin in olie.", "Voeg teriyaki saus, sojasaus en honing toe en laat kort karamelliseren.",
      "Verwarm de doperwten kort mee.", "Snijd de komkommer en lente-ui.",
      "Doe de rijst in een kom en voeg kip, komkommer en doperwten toe.", "Garneer met lente-ui en sesamzaad."],
  },
  {
    id: "kip-pesto-pastasalade", name: "Kip Pesto Pastasalade", source: "Eiwitrijke Recepten NL",
    type: "Pasta", time: 20, serv: 1, kcal: 520, p: 38, c: 50, f: 18, est: true,
    base: "#E4D7A8", pal: ["#5C7D2F", "#D14A3A", "#7FB77E", "#E4B375", "#3F7D3A"], drizzle: true,
    ing: [
      { n: "Kipfilet", a: null, u: "", c: "vv" }, { n: "Volkoren pasta", a: null, u: "", c: "pg" },
      { n: "Groene pesto", a: null, u: "", c: "sk" }, { n: "Cherrytomaatjes", a: null, u: "", c: "gf" },
      { n: "Komkommer", a: null, u: "", c: "gf" }, { n: "Rucola", a: null, u: "", c: "gf" },
      { n: "Griekse yoghurt", a: null, u: "", c: "zk" },
    ],
    steps: ["Kook de pasta.", "Bak de kip.", "Meng alles met pesto en een lepel yoghurt."],
  },
  {
    id: "burrata-tomaten-pasta", name: "Romige Burrata Tomaten Pasta", source: "MiniMeals",
    type: "Pasta", time: 25, serv: 2, kcal: 545, p: 38, c: 49, f: 20,
    base: "#C0432E", pal: ["#E9C879", "#F4EFE6", "#3F7D3A", "#D14A3A"], drizzle: false,
    ing: [
      { n: "Pasta schelpjes", a: 180, u: "g", c: "pg" }, { n: "Kipgehakt", a: 250, u: "g", c: "vv" },
      { n: "Ui", a: 1, u: "stuk", c: "gf" }, { n: "Knoflook", a: 2, u: "teen", c: "gf" },
      { n: "Passata", a: 200, u: "ml", c: "sk" }, { n: "Kookroom light", a: 75, u: "ml", c: "zk" },
      { n: "Burrata", a: 125, u: "g", c: "zk" }, { n: "Parmezaan", a: 10, u: "g", c: "zk" },
      { n: "Verse basilicum", a: 1, u: "handje", c: "gf" }, { n: "Italiaanse kruiden", a: 1, u: "tl", c: "sk" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Kook de pasta volgens de verpakking.", "Snipper de ui en hak de knoflook fijn.",
      "Bak het kipgehakt rul in een pan met peper, zout en Italiaanse kruiden.", "Voeg ui en knoflook toe en bak kort mee.",
      "Roer de passata en kookroom erdoor en laat even prutten.", "Meng de gekookte pasta door de saus.",
      "Schep op, verdeel de burrata erover en maak af met Parmezaan en basilicum.", "Serveer direct."],
  },
  {
    id: "honey-garlic-noodle", name: "Honey Garlic Chicken Noodle Bowls", source: "MacroFit",
    type: "Bowl", time: 25, serv: 4, kcal: 430, p: 38, c: 48, f: 7,
    base: "#E7C77A", pal: ["#C97A2B", "#3F7D3A", "#E08A3C", "#4E9A4A", "#EDE3C8"], drizzle: false,
    ing: [
      { n: "Kipfilet", a: 500, u: "g", c: "vv" }, { n: "Noodles", a: 180, u: "g", c: "pg" },
      { n: "Broccoli", a: 2, u: "cup", c: "gf" }, { n: "Wortel", a: 1, u: "stuk", c: "gf" },
      { n: "Lente-ui", a: 2, u: "stuk", c: "gf" }, { n: "Honing", a: 2, u: "el", c: "sk" },
      { n: "Sojasaus", a: 2, u: "el", c: "sk" }, { n: "Knoflook", a: 2, u: "teen", c: "gf" },
      { n: "Sesamolie", a: 1, u: "tl", c: "sk" }, { n: "Sesamzaad", a: 1, u: "tl", c: "sk" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Kook de noodles volgens de verpakking en giet af.", "Bak de kip 6-8 min tot gaar.",
      "Stoom de broccoli 2-3 min tot beetgaar.", "Roer knoflook, honing, sojasaus en sesamolie erdoor; laat 1-2 min glazig worden.",
      "Schep de noodles, broccoli en wortel erdoor.", "Top met sesamzaad en lente-ui."],
  },
  {
    id: "steak-frites-light", name: "Steak Frites Light", source: "MiniMeals",
    type: "Plate", time: 30, serv: 2, kcal: 495, p: 38, c: 37, f: 18,
    base: "#EFEBE2", pal: ["#6E4630", "#E7B84E", "#B5654E", "#4E9A4A"], drizzle: true,
    ing: [
      { n: "Biefstuk", a: 300, u: "g", c: "vv" }, { n: "Aardappelfriet (oven)", a: 350, u: "g", c: "gf" },
      { n: "Olijfolie", a: 1, u: "tl", c: "sk" }, { n: "Griekse yoghurt 0%", a: 80, u: "g", c: "zk" },
      { n: "Mosterd", a: 1, u: "tl", c: "sk" }, { n: "Light mayonaise", a: 1, u: "tl", c: "sk" },
      { n: "Knoflook", a: 1, u: "teen", c: "gf" }, { n: "Parmezaanse kaas", a: 10, u: "g", c: "zk" },
      { n: "Paprikapoeder", a: 1, u: "tl", c: "sk" }, { n: "Knoflookpoeder", a: 0.5, u: "tl", c: "sk" },
      { n: "Rozemarijn", a: 1, u: "takje", c: "gf" }, { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Verwarm de oven en bak de friet goudbruin en krokant volgens de verpakking.",
      "Meng de Griekse yoghurt met mosterd, light mayonaise, geperste knoflook, peper en snuf zout.",
      "Dep de biefstuk droog en kruid met paprikapoeder, knoflookpoeder, peper en zout.",
      "Verhit de olijfolie in een pan en bak de biefstuk naar wens.", "Laat het vlees kort rusten en snijd daarna in plakjes.",
      "Verdeel de friet over twee borden en strooi Parmezaanse kaas erover.", "Leg de plakjes biefstuk erbij en serveer met de saus.",
      "Maak af met wat rozemarijn en eventueel extra peper."],
  },
  {
    id: "toscaanse-mini", name: "Romige Toscaanse Kip Pasta", source: "MiniMeals",
    type: "Pasta", time: 25, serv: 2, kcal: 515, p: 41, c: 46, f: 16,
    base: "#E4CE8E", pal: ["#D14A3A", "#3F7D3A", "#E4B375", "#B96A2A"], drizzle: false,
    ing: [
      { n: "Rigatoni", a: 150, u: "g", c: "pg" }, { n: "Kipfilet", a: 250, u: "g", c: "vv" },
      { n: "Cherrytomaten", a: 100, u: "g", c: "gf" }, { n: "Spinazie", a: 75, u: "g", c: "gf" },
      { n: "Rode ui", a: 0.5, u: "stuk", c: "gf" }, { n: "Knoflook", a: 2, u: "teen", c: "gf" },
      { n: "Light kookroom", a: 100, u: "ml", c: "zk" }, { n: "Parmezaanse kaas", a: 15, u: "g", c: "zk" },
      { n: "Italiaanse kruiden", a: 1, u: "tl", c: "sk" }, { n: "Paprikapoeder", a: 0.5, u: "tl", c: "sk" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Kook de rigatoni volgens de verpakking.", "Snijd de kip in blokjes en kruid met paprikapoeder, Italiaanse kruiden, peper en zout.",
      "Bak de kip goudbruin in een pan.", "Snijd de ui fijn en bak kort mee met de knoflook.",
      "Voeg cherrytomaten en spinazie toe en laat kort slinken.", "Roer de kookroom erdoor en laat even zachtjes prutten.",
      "Meng de gekookte pasta door de saus en maak af met Parmezaanse kaas.", "Serveer direct."],
  },
  {
    id: "crispy-chicken-wrap", name: "Crispy Chicken Wrap", source: "MiniMeals",
    type: "Wrap", time: 20, serv: 2, kcal: 495, p: 34, c: 41, f: 17,
    base: "#E9D6A9", pal: ["#D68A3A", "#6DA84F", "#C0433A", "#E08A3C", "#F2E7C0"], drizzle: true,
    ing: [
      { n: "Grote wraps", a: 2, u: "stuk", c: "br" }, { n: "Krokante kipstukjes", a: 250, u: "g", c: "vv" },
      { n: "Koolslamix", a: 120, u: "g", c: "gf" }, { n: "Rode ui", a: 0.5, u: "stuk", c: "gf" },
      { n: "Rode paprika", a: 0.5, u: "stuk", c: "gf" }, { n: "Wortel julienne", a: 50, u: "g", c: "gf" },
      { n: "Griekse yoghurt", a: 80, u: "g", c: "zk" }, { n: "Knoflook", a: 1, u: "teen", c: "gf" },
      { n: "Citroensap", a: 1, u: "tl", c: "sk" }, { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Bak de krokante kip goudbruin in de oven of airfryer.", "Snijd de rode ui en paprika in dunne reepjes.",
      "Meng de Griekse yoghurt met geperste knoflook, citroensap, peper en zout.", "Verwarm de wraps kort in een droge pan.",
      "Verdeel de koolslamix over de wraps.", "Voeg de kip, paprika, ui en wortel toe.",
      "Lepel de saus erover, rol de wraps strak op en serveer direct."],
  },
  {
    id: "loaded-taco-bowl", name: "Loaded Taco Potato Bowl", source: "MiniMeals",
    type: "Bowl", time: 30, serv: 2, kcal: 505, p: 33, c: 37, f: 22,
    base: "#E3B24E", pal: ["#7A4A33", "#F2C94C", "#6DA84F", "#D14A3A", "#F4EFE6"], drizzle: true,
    ing: [
      { n: "Aardappelblokjes", a: 500, u: "g", c: "gf" }, { n: "Mager rundergehakt", a: 250, u: "g", c: "vv" },
      { n: "Tacokruiden", a: 1, u: "tl", c: "sk" }, { n: "Paprikapoeder", a: 1, u: "tl", c: "sk" },
      { n: "Komijn", a: 0.5, u: "tl", c: "sk" }, { n: "Geraspte 30+ kaas", a: 80, u: "g", c: "zk" },
      { n: "Avocado", a: 1, u: "stuk", c: "gf" }, { n: "Bosuitjes", a: 2, u: "stuk", c: "gf" },
      { n: "Tomaat", a: 1, u: "stuk", c: "gf" }, { n: "Griekse yoghurt", a: 80, u: "g", c: "zk" },
      { n: "Limoensap", a: 1, u: "tl", c: "sk" }, { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Bak de aardappelblokjes goudbruin en krokant in de oven of airfryer.",
      "Kruid het gehakt met tacokruiden, paprikapoeder, komijn, peper en zout.", "Bak het gehakt rul en gaar in een pan.",
      "Snijd de tomaat en bosui fijn en snijd de avocado in stukjes.", "Meng de Griekse yoghurt met limoensap en een snuf zout.",
      "Verdeel de krokante aardappels over twee kommen en schep het gehakt erop.", "Maak af met kaas, avocado, tomaat, bosui en de yoghurtsaus."],
  },
  {
    id: "toscaanse-snelle", name: "Romige Toscaanse Kip Pasta (zongedroogd)", source: "De Snelle Keuken",
    type: "Pasta", time: 25, serv: 1, kcal: 520, p: 42, c: 50, f: 18,
    base: "#E4CE8E", pal: ["#B5654E", "#E4B375", "#B96A2A", "#8E5AA0"], drizzle: false,
    ing: [
      { n: "Penne", a: 75, u: "g", c: "pg" }, { n: "Kipfilet", a: 120, u: "g", c: "vv" },
      { n: "Ui", a: 0.5, u: "stuk", c: "gf" }, { n: "Knoflook", a: 1, u: "teen", c: "gf" },
      { n: "Zongedroogde tomaat", a: 30, u: "g", c: "gf" }, { n: "Kookroom light", a: 40, u: "ml", c: "zk" },
      { n: "Parmezaanse kaas", a: 10, u: "g", c: "zk" }, { n: "Olijfolie", a: 1, u: "tl", c: "sk" },
      { n: "Italiaanse kruiden", a: null, u: "", c: "sk" }, { n: "Chili flakes", a: null, u: "", c: "sk" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Kook de pasta volgens de verpakking.", "Bak de kip in olijfolie goudbruin met peper, zout en Italiaanse kruiden.",
      "Voeg ui en knoflook toe en bak 2 minuten mee.", "Voeg zongedroogde tomaat en kookroom toe.",
      "Laat de saus 3-4 minuten zacht koken.", "Meng de pasta door de saus.", "Strooi Parmezaanse kaas erover."],
  },
  {
    id: "flatbread-kip", name: "Flatbread Gegrilde Kip", source: "FIT OP JE BORD",
    type: "Flatbread", time: 25, serv: 2, kcal: 560, p: 45, c: 46, f: 20,
    base: "#E7C98A", pal: ["#D68A3A", "#7FB77E", "#D14A3A", "#9C5AA0", "#F4EFE6"], drizzle: true,
    ing: [
      { n: "Kipfilets", a: 2, u: "stuk", c: "vv" }, { n: "Olijfolie", a: 1, u: "el", c: "sk" },
      { n: "Paprikapoeder", a: 1, u: "tl", c: "sk" }, { n: "Knoflookpoeder", a: 0.5, u: "tl", c: "sk" },
      { n: "Uienpoeder", a: 0.5, u: "tl", c: "sk" }, { n: "Griekse yoghurt", a: 150, u: "g", c: "zk" },
      { n: "Knoflook", a: 1, u: "teen", c: "gf" }, { n: "Citroensap", a: 1, u: "el", c: "sk" },
      { n: "Verse dille/peterselie", a: 1, u: "el", c: "gf" }, { n: "Flatbreads / pita", a: 2, u: "stuk", c: "br" },
      { n: "Komkommer", a: 0.5, u: "stuk", c: "gf" }, { n: "Tomaat", a: 1, u: "stuk", c: "gf" },
      { n: "Rode ui", a: 0.25, u: "stuk", c: "gf" }, { n: "Sla / rucola", a: null, u: "", c: "gf" },
      { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Snijd de kipfilets in reepjes of laat ze heel.", "Meng in een kom de olijfolie, paprikapoeder, knoflookpoeder, uienpoeder, zout en peper.",
      "Wrijf de kip in met de marinade.", "Verhit een grillpan op middelhoog vuur en bak de kip 6-8 min gaar en goudbruin. Laat rusten en snijd in plakjes.",
      "Meng voor de knoflooksaus de Griekse yoghurt, knoflook, citroensap, dille/peterselie, zout en peper.",
      "Verwarm de flatbreads kort in een droge pan of oven.", "Besmeer de flatbreads met de knoflooksaus.",
      "Beleg met de gegrilde kip, komkommer, tomaat, rode ui en eventueel sla of rucola. Vouw dicht en geniet!"],
  },
  {
    id: "steak-sandwich", name: "Steak Sandwich", source: "FIT OP JE BORD",
    type: "Sandwich", time: 40, serv: 2, kcal: 575, p: 44, c: 48, f: 23,
    base: "#E2B66A", pal: ["#7A4A33", "#6DA84F", "#D14A3A", "#9C5AA0", "#F1E3B0"], drizzle: false,
    ing: [
      { n: "Ciabatta broodjes", a: 2, u: "stuk", c: "br" }, { n: "Biefstuk", a: 300, u: "g", c: "vv" },
      { n: "Olijfolie", a: 1, u: "el", c: "sk" }, { n: "Knoflookpoeder", a: 1, u: "tl", c: "sk" },
      { n: "Paprikapoeder", a: 1, u: "tl", c: "sk" }, { n: "Rucola / sla", a: 2, u: "handje", c: "gf" },
      { n: "Tomaat", a: 1, u: "stuk", c: "gf" }, { n: "Rode ui", a: 0.5, u: "stuk", c: "gf" },
      { n: "Light mayonaise", a: 2, u: "el", c: "sk" }, { n: "Mosterd", a: 1, u: "tl", c: "sk" },
      { n: "Augurk", a: 1, u: "tl", c: "gf" }, { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Haal de biefstuk 30 minuten van tevoren uit de koelkast.",
      "Dep de biefstuk droog en wrijf in met olijfolie, knoflookpoeder, paprikapoeder, zout en peper.",
      "Verhit een grillpan op hoog vuur en bak de biefstuk 2-3 min per kant voor medium-rare.",
      "Laat de biefstuk 5 min rusten onder folie en snijd daarna in dunne plakjes.",
      "Meng in een kommetje de light mayonaise, mosterd en augurk.",
      "Snijd de ciabatta doormidden en rooster ze kort tot licht krokant.", "Besmeer beide helften met de saus.",
      "Beleg met rucola, tomaat, rode ui en de plakjes biefstuk.", "Dek af met de bovenkant van het brood en geniet!"],
  },
  {
    id: "zoete-aardappel-beef", name: "Zoete Aardappel Beef Bowl", source: "De Snelle Keuken",
    type: "Bowl", time: 25, serv: 1, kcal: 550, p: 42, c: 35, f: 28,
    base: "#EFE6CF", pal: ["#E08A3C", "#7A4A33", "#6DA84F", "#F4EFE6", "#EDE3C8"], drizzle: true,
    ing: [
      { n: "Mager rundergehakt", a: 125, u: "g", c: "vv" }, { n: "Zoete aardappel", a: 200, u: "g", c: "gf" },
      { n: "Cottage cheese", a: 75, u: "g", c: "zk" }, { n: "Avocado", a: 0.5, u: "stuk", c: "gf" },
      { n: "Olijfolie", a: 1, u: "tl", c: "sk" }, { n: "Paprikapoeder", a: null, u: "", c: "sk" },
      { n: "Knoflookpoeder", a: null, u: "", c: "sk" }, { n: "Zero chili saus", a: null, u: "", c: "sk" },
      { n: "Sesamzaad", a: null, u: "", c: "sk" }, { n: "Peper & zout", a: null, u: "", c: "sk" },
    ],
    steps: ["Snijd de zoete aardappel in blokjes.", "Bak de zoete aardappel goudbruin in olijfolie met paprikapoeder, knoflookpoeder, peper en zout.",
      "Bak het gehakt rul in een pan met peper en zout.", "Snijd de avocado in blokjes.", "Doe de zoete aardappel in een kom.",
      "Voeg het gehakt, de avocado en cottage cheese toe.", "Voeg eventueel wat chili saus en sesamzaad toe."],
  },
];

export const RECIPES: Recipe[] = sourceRecipes.map((recipe) => ({
  ...recipe,
  photo: `/dishes/${recipe.id}.jpg`,
}));

export const RECIPE_TYPES = Array.from(new Set(RECIPES.map((recipe) => recipe.type)));
